//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fotomarket.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fotomarketEntities : DbContext
    {
        public fotomarketEntities()
            : base("name=fotomarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Table_Admin> Table_Admin { get; set; }
        public virtual DbSet<Table_AksiyonKameralari> Table_AksiyonKameralari { get; set; }
        public virtual DbSet<Table_AynasizFotografMakineleri> Table_AynasizFotografMakineleri { get; set; }
        public virtual DbSet<Table_CokSatanlar> Table_CokSatanlar { get; set; }
        public virtual DbSet<Table_Dronelar> Table_Dronelar { get; set; }
        public virtual DbSet<Table_DSLRFotografMakineleri> Table_DSLRFotografMakineleri { get; set; }
        public virtual DbSet<Table_Hakkimizda> Table_Hakkimizda { get; set; }
        public virtual DbSet<Table_Iletisim> Table_Iletisim { get; set; }
        public virtual DbSet<Table_IletisimBilgileri> Table_IletisimBilgileri { get; set; }
        public virtual DbSet<Table_Kaynaklar> Table_Kaynaklar { get; set; }
        public virtual DbSet<Table_Kullanicilar> Table_Kullanicilar { get; set; }
        public virtual DbSet<Table_Lensler> Table_Lensler { get; set; }
        public virtual DbSet<Table_Markalar> Table_Markalar { get; set; }
        public virtual DbSet<Table_VideoKameralar> Table_VideoKameralar { get; set; }
        public virtual DbSet<Table_Videolar> Table_Videolar { get; set; }
    }
}
