//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fotomarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_IletisimBilgileri
    {
        public int ID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public string TelefonNumarasi { get; set; }
        public string EpostaAdresi { get; set; }
    
        public virtual Table_Admin Table_Admin { get; set; }
    }
}
