//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fotomarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Markalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Markalar()
        {
            this.Table_AksiyonKameralari = new HashSet<Table_AksiyonKameralari>();
            this.Table_AynasizFotografMakineleri = new HashSet<Table_AynasizFotografMakineleri>();
            this.Table_CokSatanlar = new HashSet<Table_CokSatanlar>();
            this.Table_Dronelar = new HashSet<Table_Dronelar>();
            this.Table_DSLRFotografMakineleri = new HashSet<Table_DSLRFotografMakineleri>();
            this.Table_Lensler = new HashSet<Table_Lensler>();
            this.Table_VideoKameralar = new HashSet<Table_VideoKameralar>();
        }
    
        public int ID { get; set; }
        public string MarkaAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_AksiyonKameralari> Table_AksiyonKameralari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_AynasizFotografMakineleri> Table_AynasizFotografMakineleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_CokSatanlar> Table_CokSatanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Dronelar> Table_Dronelar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_DSLRFotografMakineleri> Table_DSLRFotografMakineleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Lensler> Table_Lensler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_VideoKameralar> Table_VideoKameralar { get; set; }
    }
}
