//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fotomarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_CokSatanlar
    {
        public System.Guid ID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> MarkaID { get; set; }
        public string MarkaAdi { get; set; }
        public string ModelAdi { get; set; }
        public string UrunFiyati { get; set; }
        public string UrunGorseli { get; set; }
    
        public virtual Table_AksiyonKameralari Table_AksiyonKameralari { get; set; }
        public virtual Table_AynasizFotografMakineleri Table_AynasizFotografMakineleri { get; set; }
        public virtual Table_Dronelar Table_Dronelar { get; set; }
        public virtual Table_DSLRFotografMakineleri Table_DSLRFotografMakineleri { get; set; }
        public virtual Table_Lensler Table_Lensler { get; set; }
        public virtual Table_Markalar Table_Markalar { get; set; }
        public virtual Table_VideoKameralar Table_VideoKameralar { get; set; }
    }
}
